blog/urls.py
from django.urls import path, re_path

from . import views
from .feeds import LatestPostsFeed

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="post_list"),
    path("tag/<tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

images/urls.py
from django.urls import path

from . import views

app_name = 'images'
urlpatterns = [
    path('create/',views.image_create,name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('',views.image_list, name='list'),
    path('ranking/',views.image_ranking,name='ranking'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from payment import webhooks

sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
    path("account/", include("account.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path('images/',include('images.urls', namespace='images')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('shop/',include('shop.urls',namespace='shop')),
    path(_('cart/'),include('cart.urls',namespace='cart')),
    path(_('orders/'),include('orders.urls',namespace='orders')),
    path(_('payment/'),include('payment.urls',namespace='payment')),
    path(_('coupons/'),include('coupons.urls',namespace='coupons')),
    path('rosetta/',include('rosetta.urls')),
)

urlpatterns += [
    path('webhook/',webhooks.stripe_webhook,name='stripe-webhook'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


# Create your models here.
class Image(models.Model):
    # 해당 이미지를 등록한 사용자이며 일대다의 관계를 가진다. 사용자는 다 이미지, 이미지는 일 사용자
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="images_created",
        on_delete=models.CASCADE,
    )
    # 이미지 제목
    title = models.CharField(max_length=200)
    # URL을 만들기 위한 짧은 레이블
    slug = models.SlugField(max_length=200, blank=True)
    # 이미지의 원본 URL
    url = models.URLField(max_length=2000)
    # 이미지 파일
    image = models.ImageField(upload_to="images/%Y/%m/%d")
    # 이미지의 설명
    description = models.TextField(blank=True)
    # 데이터베이스에 등록된 날짜
    created = models.DateField(auto_now_add=True)

    users_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="images_liked", blank=True
    )
    total_likes = models.PositiveBigIntegerField(default=0)

    class Meta:
        # created 필드에 대한 내림차순으로 데이터베이스 인덱스를 정의
        # 인덱스는 쿼리 성능을 향상시키기 때문에 조건으로 자주 사용하는 필드에 대해 인덱스를 생성하는 것이 좋다.
        indexes = [
            models.Index(fields=["-created"]),
            models.Index(fields=['-total_likes']),
        ]
        ordering = ["-created"]

    def __str__(self):
        return self.title

    # save()메서드를 재정의 하여 title 필드의 값을 기반으로 slug 필드를 채워서 생성
    # slug 필드에 값이 없는 경우, slugify()함수를 사용하여 이미지의 제목에서 자동으로 슬러그를 생성
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)  # 슬러스를 먼저 채우고
        super().save(*args, **kwargs)  # 객체 저장

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify
import requests

from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["title", "url", "description"]
        # 사용자는 폼에서 직접 이미지 URL을 입력하지 않고 외부 사이트에서 아미지를 선택할 수있는 자바스크립트 도구를 사용
        widgets = {
            "url": forms.HiddenInput,
        }

    def clean_url(self):
        # url 필드의 값을 폼 인스턴스의 cleaned_data 사전에서 가져옴
        url = self.cleaned_data["url"]
        valid_extensions = ["jpg", "jpeg", "png"]
        # url 을 분할하여 확장명 검사
        extension = url.rsplit(".", 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError(
                "The given URL does not match valid image extensions."
            )
        return url

    def save(self, force_insert=False, force_update=False, commit=False):
        image = super().save(commit=False)
        image_url = self.cleaned_data["url"]
        name = slugify(image.title)
        extension = image_url.rsplit(".", 1)[1].lower()
        image_name = f"{name}.{extension}"
        # URL 에서 이미지 다운로드 (get요청을 보내서 이미지를 다운로드)
        response = requests.get(image_url)
        # 다운로드한 파일 내용으로 ContentFile 객체를 생성, 파일이 프로젝트의 미지어 디렉토리에 저장되며 데이터 베이스에는 저장하지 않는다.
        image.image.save(image_name, ContentFile(response.content), save=False)
        # commite 이 True 일때만 데이터베이스에 저장
        if commit:
            image.save()
        return image

images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
import redis

from .forms import ImageCreateForm
from .models import Image
from actions.utils import create_action
from mysite import settings

# Create your views here.

# connect to redis
r = redis.Redis(host=settings.REDIS_HOST,port=settings.REDIS_PORT,db=settings.REDIS_DB)

# 로그인 상태여야 이미지를 등록 할 수 있다
@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            create_action(request.user,'bookmarked image',new_image)
            messages.success(request,'Image added successfully')
            return redirect(new_image.get_absolute_url())
    else:
        # 초기 데이터를 get http 요청을 통해 제공되어야 폼의 인스턴스를 생성할 수 있다. 이 데이터는 외부 웹 사이트의 이미지의 url과 title 속성으로 구성된다.
        form = ImageCreateForm(data=request.GET)
    return render(request,'images/image/create.html',{'section':'iamges','form':form})

def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    # increment total image views by 1
    # incr()명령은 주어진 키의 값을 1씩 증가 시키고 키가 존재하지 않는다면 incr 명령이 키를 생성한다.
    # incr()메서드는 작업을 수생한 후 키의 최종값을 반환한다.
    total_views = r.incr(f'image:{image.id}:views')
    # increment image ranking by 1
    # zincrby() 명령을 사용하여 image_ranking 이라는 정렬된 집합에 이미지 조회수를 저장
    # 이미지 ID와 관련된 점수로 1을 추가하고 이를 정렬된 집합의 해당 요소의 총 점수에 더한다.
    # 이를 통해 전역적으로 모든 이미지 조회수를 추적하고 총 조회수를 기준으로 정렬된 집합을 유지할 수있게 된다.
    r.zincrby('image_ranking',1,image.id)
    return render(request,
                  'images/image/detail.html',
                  {'section': 'images', 'image': image,'total_views':total_views})
    
@login_required
def image_ranking(request):
    # get image ranking dectionary
    # zrange() 명령을 사용하여 정렬된 집합의 요소를 가져온다.
    image_ranking = r.zrange('image_ranking',0,-1,desc=True)[:10]
    # 가져온 이미지 ID를 정수 리스트로 저장
    image_ranking_ids = [int(id) for id in image_ranking]
    # get most viewed images
    # 해당 ID를 가진 image 객체를 가져와서 쿼리셋을 리스트로 변환
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    
    return render(request,'images/image/ranking.html',{'section':'images','most_viewed':most_viewed})
    
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')

    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user,'likes',image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Image.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})

@login_required
def image_list(request):
    # total_likes 필드를 이용한 좋아요수 정렬
    # images_by_popularity = Image.objects.annotate(likes=Count('users_like')).order_by('-likes')
    # or
    # images_by_popularity = Image.objects.order_by('-total_likes')
    
    images = Image.objects.all()
    paginator = Paginator(images,8)
    page = request.GET.get('page')
    images_only = request.GET.get('images_only')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    if images_only:
        return render(request, 'images/image/list_images.html', {'section':images,'images': images})
    return render(request, 'images/image/list.html', {'section':images,'images': images})

images/templates/images/image/create.html
{% extends 'base.html' %}

{% block title %}Blog an image{% endblock title %}

{% block content %}
    <h1>Blog an image</h1>
    <img src="{{ request.GET.url }}" class='image-preview'>
    <form  method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

images/templates/images/image/detail.html
{% extends "base.html" %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}
    <h1>{{ image.title }}</h1>
    {% load thumbnail %}
    <a src="{{ image.image.url }}">
        <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
    </a>
    {% with total_likes=image.users_like.count users_like=image.users_like.all %}
        <div class="image-info">
            <div>
                <span class="count">
                <span class="total">{{ total_likes }}</span>
                like{{ total_likes|pluralize }}
                </span>
                <span class="count">
                    {{ total_views }} view{{ total_views|pluralize }}
                </span>
            </div>
            <a href="#" data-id={{ image.id }} data-action='{% if request.user in users_like %}un{% endif %}like' class='like button'>
                {% if request.user not in users_like %}
                Like
                {% else %}
                Unlike
                {% endif %}
            </a>
            {{ image.description|linebreaks }}
        </div>
        <div class="image-likes">
            <hr>
            Like users
            {% for user in users_like %}
                    <p>
                    {% if user.profile.photo %}
                        <img src="{{ user.profile.photo.url }}" style='height:25px; width:25px;'>
                    {% endif %}
                    {{ user.first_name }}</p>
            {% empty %}
                Nobody likes this image yet.
            {% endfor %}
        </div>
    {% endwith %}
{% endblock %}

{% block domready %}
    const url = '{% url "images:like" %}';
    var options = {
        method: 'POST',
        headers: {'X-CSRFToken': csrftoken},
        mode: 'same-origin'
    }
    document.querySelector('a.like').addEventListener('click', function(e){
        e.preventDefault();
        var likeButton = this;
        {% comment %}add request body {% endcomment %}
        var formData = new FormData();
        formData.append('id', likeButton.dataset.id);
        formData.append('action', likeButton.dataset.action);
        options['body'] = formData;
        {% comment %} send HTTP request {% endcomment %}
        fetch(url, options).then(response => response.json()).then(data => {
            if (data['status'] === 'ok'){
                var previousAction = likeButton.dataset.action;
                {% comment %} toggle button text and data-action {% endcomment %}
                var action = previousAction === 'like' ? 'unlike' : 'like';
                likeButton.dataset.action = action;
                likeButton.innerHTML = action;
                {% comment %} update like count {% endcomment %}
                var likeCount = document.querySelector('span.count .total');
                var totalLikes = parseInt(likeCount.innerHTML);
                likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
            }
        })
    });
{% endblock domready %}

images/templates/images/image/list.html
{% extends 'base.html' %}

{% block title %}Images bookmarked{% endblock title %}

{% block content %}
    <h1>Images bookmarked</h1>
    <div id="image-list">
        {% include 'images/image/list_images.html' %}
    </div>
{% endblock content %}

{% block domready %}
    var page = 1;
    var emptyPage = false;
    var blockRequest = false;
    window.addEventListener('scroll',function(e) {
        var margin = document.body.clientHeight - window.innerHeight -200;
        if(window.pageYOffset > margin && !emptyPage && !blockRequest){
            blockRequest = true;
            page += 1;
            fetch('?images_only=1&page=' + page).then(response => response.text()).then(html => {
                if (html === '') {
                    emptyPage = true;
                }
                else {
                    var imageList = document.getElementById('image-list');
                    imageList.insertAdjacentHTML('beforeEnd',html);
                    blockRequest = false;
                }
            })
        }
    });
    {% comment %} Launch scroll event {% endcomment %}
    const scrollEvent = new Event('scroll');
    window.dispatchEvent(scrollEvent);
{% endblock domready %}

images/templates/images/image/list_images.html
{% load thumbnail %}

{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image 300x300 crop='smart' as im %}
            <a href="{{ image.get_absolute_url }}">
                <img src="{{ im.url }}">
            </a>
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class='title'>
                {{ image.title }}
            </a>
        </div>
    </div>
{% endfor %}

images/templates/images/image/ranking.html
{% extends 'base.html' %}

{% block title %}Images ranking{% endblock title %}

{% block content %}
    <h1>Images ranking</h1>
    <ol>
        {% for image in most_viewed %}
            <li>
                <a href="{{ image.get_absolute_url }}">
                    {{ image.title }}
                </a>
            </li>
        {% endfor %}
    </ol>
{% endblock content %}