blog/urls.py
from django.urls import path, re_path

from . import views
from .feeds import LatestPostsFeed

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="post_list"),
    path("tag/<tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from payment import webhooks

sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
    path("account/", include("account.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path('images/',include('images.urls', namespace='images')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('shop/',include('shop.urls',namespace='shop')),
    path(_('cart/'),include('cart.urls',namespace='cart')),
    path(_('orders/'),include('orders.urls',namespace='orders')),
    path(_('payment/'),include('payment.urls',namespace='payment')),
    path(_('coupons/'),include('coupons.urls',namespace='coupons')),
    path('rosetta/',include('rosetta.urls')),
)

urlpatterns += [
    path('webhook/',webhooks.stripe_webhook,name='stripe-webhook'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

from taggit.managers import TaggableManager


# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    # 글의 현재 상태
    class Status(models.TextChoices):
        # 임시저장 글
        DRAFT = "DF", "Draft"
        # 게시된글
        PUBLISHED = "PB", "Published"
        # Post.Status.names = ['DRAFT','PUBLISHED']

    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250, allow_unicode=True, unique_for_date="publish"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    tags = TaggableManager()

    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT
    )

    # 기본매니저
    objects = models.Manager()  # 커스텀 매니저 사용할때 필수로 기본매니저도 정의
    # 사용자 정의 매니저
    published = PublishedManager()  # 사용법 Post.published.filter()

    # 장고 기본 유저 모델을 사용
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    # related_name -> 외래키에서 접근할때 사용할 이름

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"]),
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.db.models import Count  # Django ORM의 Count 집계 함수
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import SearchVector  # 여러 필드에 대한 검색을 해주는 모듈
from django.contrib.postgres.search import SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity

from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm

# Create your views here.


def post_list(request, tag_slug=None):
    post_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    # 페이지당 3개의 게시물로 페이지네이션
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get("page", 1)

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger or TypeError:
        # page_number가 정수가 아닌 경우 첫 번째 페이지 제공
        posts = paginator.page(1)
    except EmptyPage:
        # page_number가 범위를 벗어난 경우 결과의 마지막 페이지 제공
        posts = paginator.page(paginator.num_pages)
    return render(request, "blog/post/list.html", {"posts": posts, "tag": tag})


# def post_detail(request, id):
#     try:
#         post = Post.published.get(id=id)
#     except Post.DoesNotExist:
#         raise Http404("No Post found.")
#     return render(request, "blog/post/detail.html", {"post": post})


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=slug,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    comments = post.comments.filter(active=True)
    form = CommentForm()

    # 현재 포스트의 태그를 기준으로 검색 values_list() 쿼리셋은 주어진 필드의 값을 튜플로 반환, flat=True 는 튜플을 (1,)과같은 원소가 아닌 1과 같은 단일값을 얻는다.
    post_tags_ids = post.tags.values_list("id", flat=True)

    # 태그중 하나라도 포함된 모든 포스터를 가져오며 현재 포스트는 제외
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)

    # Count 집계 함수를 사용하여 공유 태그 수를 나타내는 calculated 필드인 same_tags를 생성
    # 공유 태그 수로 정렬 후 수가 같다면 최근 포스트를 먼저 표시하며 결과는 4개만 출력
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]

    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "comments": comments,
            "form": form,
            "similar_posts": similar_posts,
        },
    )


def post_share(request, post_id):
    # id로 글 검색
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        # 폼 제출
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # 폼 필드가 유효한 경우
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']}님이 {post.title}을(를) 추천합니다."
            message = f"{post.title}을(를) 다음에서 읽어보세요.\n\n {cd['name']}의 의견 : {cd['comments']} \n\n {cd['name']}님의 email 주소 : {cd['email']}"
            send_mail(
                subject, message, f"{cd['name']}<1@1>", [cd["to"]]
            )  # cd['email] 불필요 구글 smtp 등로고딘 구글 계정만 보낸사람으로 나옴 email 칸에 아무리 다른걸 써도 smtp 구글 계정만 보낸사람으로 출력
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(
        request,
        "blog/post/comment.html",
        {"post": post, "form": form, "comment": comment},
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            results = (
                Post.published.annotate(
                    similarity=TrigramSimilarity("title", query),
                )
                .filter(similarity__gt=0.1)
                .order_by("-similarity")
            )
            # 형태소 추출 후 SearchRank를 사용하여 결과를 관련성에 따라 순위 지정
            # 제목 검색 벡터에 가중치 'A'를 적용하고 본문 검색 벡터에 가중치 'B'를 적용
            # 제목 일치는 본문 일치보다 우선하며, 결과를 필터링하여 순위가 0.3보다 높은 결과만 표시

    return render(
        request,
        "blog/post/search.html",
        {"form": form, "query": query, "results": results},
    )


class PostListView(ListView):
    queryset = Post.published.all().order_by("-updated")
    context_object_name = "posts"
    paginate_by = 3
    template_name = "blog/post/list.html"

blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}

{% block title %}Add a comment{% endblock title %}

{% block content %}
{% if comment %}
<h2>Your comment has been added.</h2>
<p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
{% else %}
    {% include 'blog/post/includes/comment_form.html' %}
{% endif %}
{% endblock content %}

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown}} 
{% comment %} |markdown 이 필터는 줄바꿈을 p태그로 변환할 뿐만 아니라 markdown 서식도 HTML로 변환 {% endcomment %}
<p>
    <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
</p>
<h2>Similar posts</h2>
{% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    There are no similar posts yet.
{% endfor %}
{% with comments.count as total_comments %}
    <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
{% endwith %}
{% for comment in comments %}
    <div class="comment">
        <p class="info"> Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }} </p> 
        {{ comment.body|linebreaks }} 
    </div> {% empty %} 
    <p>There are no comments.</p> 
{% endfor %} 
{% include 'blog/post/includes/comment_form.html' %}
{% endblock content %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block title %}My Blog{% endblock title %}

{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="tags">
            Tags : 
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
            {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords:30}}
        {% comment %} |markdown 이 필터는 markdown 내용을 HTML로 변환한다. {% endcomment %}
    {% endfor %}
    {% include 'pagination.html' with page=page_obj %}
{% endblock content %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block title %}Search{% endblock title %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{total_results|pluralize}}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value='Search'>
        </form>
    {% endif %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share a post{% endblock title %}

{% block content %}
{% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
        "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
{% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
    </form>
{% endif %}
{% endblock content %}