blog/urls.py
from django.urls import path, re_path

from . import views
from .feeds import LatestPostsFeed

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="post_list"),
    path("tag/<tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from payment import webhooks

sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
    path("account/", include("account.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path('images/',include('images.urls', namespace='images')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('shop/',include('shop.urls',namespace='shop')),
    path(_('cart/'),include('cart.urls',namespace='cart')),
    path(_('orders/'),include('orders.urls',namespace='orders')),
    path(_('payment/'),include('payment.urls',namespace='payment')),
    path(_('coupons/'),include('coupons.urls',namespace='coupons')),
    path('rosetta/',include('rosetta.urls')),
)

urlpatterns += [
    path('webhook/',webhooks.stripe_webhook,name='stripe-webhook'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views
from . import webhooks

app_name = 'payment'
urlpatterns = [
    path(_('process/'),views.payment_process,name='process'),
    path(_('completed/'),views.payment_completed,name='completed'),
    path(_('canceled/'),views.payment_canceled,name='canceled'),
]

payment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from decimal import Decimal
from django.urls import reverse

import stripe

from orders.models import Order
from mysite import settings

# Create your views here.

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

def payment_process(request):
    order_id = request.session.get('order_id',None)
    order = get_object_or_404(Order,id=order_id)
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))

        # Stripe checkout session data
        session_data = {
            'mode':'payment',
            'client_reference_id':order.id,
            'success_url':success_url,
            'cancel_url':cancel_url,
            'line_items':[]
        }
        # 주문 항목을 Stripe checkout 세션에 추가
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data':{
                    'unit_amount':int(item.price * Decimal('100')),
                    'currency':'usd',
                    'product_data':{
                        'name':item.product.name,
                    },
                },
                'quantity':item.quantity,
            })
        if order.coupon:
            # 쿠폰이 있는 경우 stripe.Coupon.create()를 사용하여 쿠폰을 생성
            # name - 주문 객체의 쿠폰 코드, percent_off - 주문 객체의 할인율, duration - 일회성 쿠폰임을 인식
            stripe_coupon = stripe.Coupon.create(name=order.coupon.code,percent_off=order.discount,duration='once',)
            # 쿠폰을 생성한 후 해당 쿠폰의 id를 session_data 딕셔너리에 추가
            session_data['discounts'] = [{'coupon':stripe_coupon.id}]
        # create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)
        # redirect to Stripe payment form
        return redirect(session.url,code=303)
    else:
        return render(request,'payment/process.html',locals())

def payment_completed(request):
    return render(request,'payment/completed.html')

def payment_canceled(request):
    return render(request,'payment/canceled.html')

payment/templates/payment/canceled.html
{% extends 'shop/base.html' %}

{% block title %}Canceled{% endblock title %}

{% block content %}
    <h1>Your payment has not been processed</h1>
    <p>There was a problem processing your payment.</p>
{% endblock content %}

payment/templates/payment/completed.html
{% extends 'shop/base.html' %}

{% block title %}Completed{% endblock title %}

{% block content %}
    <h1>Your payment has been successfully</h1>
    <p>Your payment has been successfully.</p>
{% endblock content %}

payment/templates/payment/process.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}Order Payment{% endblock title %}

{% block content %}
    <h1>Order</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
                <tr class="row{% cycle '1' '2' %}">
                    <td>
                        <img src="{% if item.product.image %}{{ item.product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" >
                    </td>
                    <td>{{ itam.product.name }}</td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">{{ item.quantity }}</td>
                    <td class="num">${{ item.get_cost }}</td>
                </tr>
            {% endfor %}
            {% if order.coupon %}
                <tr class="subtotal">
                    <td>Subtotal</td>
                    <td colspan='3'></td>
                    <td class="num">${{ order.get_total_cost_before_discount|floatformat:2 }}</td>
                </tr>
                <tr>
                    <td>"{{ order.coupon.code }}" coupon ({{ order.discount }}% off)</td>
                    <td colspan='3'></td>
                    <td class="num neg">- ${{ order.get_discount|floatformat:2 }}</td>
                </tr>
            {% endif %}
            <tr class="total">
                <td colspan='4'>Total</td>
                <td class="num">${{ order.get_total_cost }}</td>
            </tr>
        </tbody>
    </table>
    <form action="{% url 'payment:process' %}" method='post'>
        <input type="submit" value="Pay">
        {% csrf_token %}
    </form>
{% endblock content %}